### PR TITLE
Update torrgrab.py

### PR DESCRIPTION
**Pull request by priyamharsh14**
Enhanced CLI (with awesome banner)

### CODE REVIEW

**Comment by PradumnUpadhyay** [comment]
> Enhanced CLI (with awesome banner)
can you include qbittorrent or utorrent API as we tried and it didn't work out, and it will be convenient also for users who don't have the torrent app installed on their system

**Comment by priyamharsh14** [comment]
Provide me the exact thing you want me to add in to the code.

**Comment by PradumnUpadhyay** [comment]
> Provide me the exact thing you want me to add in to the code.

Here is the API link https://pypi.org/project/python-qbittorrent/

**Comment by priyamharsh14** [comment]
How exactly you want to use that API. That API acts as a client system to WEB UI of torrent software and it needs torrent software to be installed on the system.

**Comment by PradumnUpadhyay** [comment]
> How exactly you want to use that API. That API acts as a client system to WEB UI of torrent software and it needs torrent software to be installed on the system.

Yeah I tried that too by altering web UI also it didn't work, but any idea how can we make it CLI based

**Comment by priyamharsh14** [comment]
So.. you want to create interface to that WEB UI in CLI mode ??

**Comment by TheSpeedX** [comment]
@priyamharsh14 Great To See You here

Actually i wanna download Torrent Files Without Any Stuff That Needs GUI
So that we can download data in CLI Mode.

**Comment by priyamharsh14** [comment]
@TheSpeedX Yo !

I can try to implement the CLI version of that qbit torrent API
but it will still require to have a torrent software installed on the system and it must have the WEB UI option turned on.

**Pull request merged**
